language: ruby
rvm:
- 2.3.3
before_install:
- openssl aes-256-cbc -K $encrypted_740c69c22170_key -iv $encrypted_740c69c22170_iv
  -in config/secrets.yml.enc -out config/secrets.yml -d
- openssl aes-256-cbc -K $encrypted_740c69c22170_key -iv $encrypted_740c69c22170_iv
  -in config/database.yml.enc -out config/database.yml -d
