default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: catty_novel_development
  username: postgres
  password: 24373514
  host: 127.0.0.1
  
test:
  <<: *default
  database: catty_novel_test
  username: postgres
  password: 24373514
  host: 127.0.0.1

production:
  <<: *default
  database: catty_novel_production
  username: vfgcees
  password: reireirei0
  host: 127.0.0.1