development: &development
  cipher: AES-256-CBC
  tasks:
    -
      encrypt_from: config/database.yml
      encrypt_to: config/database.yml.enc
    -
      encrypt_from: config/secrets.yml
      encrypt_to: config/secrets.yml.enc
      
test:
  <<: *development
production:
  <<: *development
